[package]
name = "hlswbhk"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.8", features = ["macros"] }
chrono = { version = "0.4.44", features = ["serde"] }
dotenvy = "0.15.7"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
sqlx = { version = "0.8.6", features = [ "sqlite", "runtime-tokio"] }
tokio = { version = "1.49.0", features = ["full"] }
uuid = { version = "1.0", features = ["v4", "serde"] }
